### ISSUE TITLE
Tag all regular expression related tools with regexp

### ISSUE THREAD

**Issue by schalkneethling** [schalkneethling/developer-toolchest#191]
There are currently two tools in the JSON database related to regular expressions. If you search for `regexp` only one is shown, while searching for `regex` returns both. We should tag both with both terms and ensure we do this with any future regular expression tools.

**Comment by Rico-Smit** [comment]
I would like to fix this error. :)

**Comment by schalkneethling** [comment]
> I would like to fix this error. :)

Go for it!
