### ISSUE TITLE
chore: change JSONVisio to JSON Crack and update link

### ISSUE THREAD

**Issue by schalkneethling** [schalkneethling/developer-toolchest#251]
URL: https://developer-toolchest.com/?q=json

One of the tools listed is JSONVision. This has been rebranded to JSON Crack and can now be found at https://jsoncrack.com/

- [ ] Change the name from JSONVisio to JSON Crack
- [ ] Update the link to point to https://jsoncrack.com/

**Comment by rohit-rambade** [comment]
Hello @schalkneethling  I'll like to work on this
